app:
  env: dev
  name: template-server
  log:
    log_level: debug
    path: "./resources/applog/server.log"
    max_size: 100 # 单个日志文件最大100M
    max_age: 60 # 备份文件最多保存60天
  pagination:
    default_size: 20
    max_size: 100

database:
  type: mysql
  master:
    dsn: root:superpass@tcp(localhost:30306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    max_open: 100
    max_idle: 10
    max_life_time: 300000000 # 300s 内可复用
  slave:
    dsn: root:superpass@tcp(localhost:30306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    max_open: 100
    max_idle: 10
    max_life_time: 300000000

redis: # 记得更改成自己的连接配置
  addr: 127.0.0.1:31379
  password: 123456
  pool_size: 10
  db: 0